spring.application.name=sendly
spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:10367/railway
spring.datasource.username=root
spring.datasource.password=TJDLOtntZBVqGDHwzHqTQMdVocdOlYoc
server.port=${PORT:3306}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=sendlyenvios@gmail.com
spring.mail.password=papcxhtilzrugvlo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false